version: '3.9'

services:
  frontend:
    container_name: latest-earthquakes-ph-frontend
    build:
      context: ../front-end
      dockerfile: Dockerfile
    image: "latest-earthquakes-ph-frontend"
    depends_on:
      - "backend"
    ports:
      - "443:443"
    networks:
      app-network:
        ipv4_address: 172.22.0.2
    volumes:
      - type: bind
        source: ../front-end/certs
        target: /etc/nginx/certs

  backend:
    container_name: latest-earthquakes-ph-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: "latest-earthquakes-ph-backend"
    depends_on:
      - "mongodb"
      - "redis"
    expose:
      - "5000"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    networks:
      app-network:
        ipv4_address: 172.22.0.3

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb-data:/data/db
    expose:
      - "27017"
    networks:
      app-network:
        ipv4_address: 172.22.0.4

  redis:
    container_name: redis
    image: redis
    expose:
      - "6379"
    networks:
      app-network:
        ipv4_address: 172.22.0.5

  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:3.7
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb
    environment:
      - PBF_URL=http://download.geofabrik.de/asia/philippines-latest.osm.pbf
      - REPLICATION_URL=http://download.geofabrik.de/asia/philippines-updates/
      - IMPORT_WIKIPEDIA=false
      - NOMINATIM_PASSWORD=sysop
      - POSTGRES_MAINTENANCE_WORK_MEM=4GB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=8GB
    expose:
      - "8080"
    networks:
      app-network:
        ipv4_address: 172.22.0.6
      
volumes:
  mongodb-data:
  nominatim-data:

networks:
  app-network:
    name: latest-earthquakes-ph
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

      

