version: '3.9'

services:
  backend:
    container_name: latest-earthquakes-ph-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: "base" # select dockerfile stage to use
    image: "latest-earthquakes-ph-backend-dev:latest"
    volumes:
      # bind local dir to reflect changes in container
      - ./:/app
    depends_on:
      - "mongodb"
      - "redis"
      - "mysql"
    expose:
      - "5000"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    networks:
      app-network:
        ipv4_address: 172.22.0.3
    # set command to only install node_modules if not present, then startDev
    command: sh -c '[ -d "node_modules" ] && npm run startDev
                    || npm ci && npm run startDev'

  mongodb:
    container_name: mongodb
    image: "mongo:4.4.12"
    volumes:
      - mongodb-data:/data/db
    expose:
      - "27017"
    networks:
      app-network:
        ipv4_address: 172.22.0.4
    command: --quiet # reduce logs

  redis:
    container_name: redis
    image: "redis:6.2.5"
    expose:
      - "6379"
    networks:
      app-network:
        ipv4_address: 172.22.0.5

  mysql:
    container_name: mysql
    image: "mysql:8.0.32"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${DB_USER} # will automatically be replaced by values in .env in the same dir
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      # init db contents by binding sample seiscomp data from host into docker-entrypoint-initdb.d
      - ./dev/sample_data/seiscompDB.sql:/docker-entrypoint-initdb.d/seiscompDB.sql
    ports:
      - "3306:3306" # like in production, mysql should be connectable through "host.docker.internal:host-gateway"
                    # this mirrors a mysql service running locally on host machine

volumes:
  mongodb-data:

networks:
  app-network:
    name: latest-earthquakes-ph
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16


