version: '3.9'

services:
  frontend:
    container_name: latest-earthquakes-ph-frontend
    build:
      context: ../front-end
      dockerfile: Dockerfile
    image: "latest-earthquakes-ph-frontend:latest"
    depends_on:
      - "backend"
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    networks:
      app-network:
        ipv4_address: 172.22.0.2
    volumes:
      - ./https_data/nginx:/etc/nginx/conf.d
      - ./https_data/certbot/conf:/etc/letsencrypt
      - ./https_data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./https_data/certbot/conf:/etc/letsencrypt
      - ./https_data/certbot/www:/var/www/certbot

  backend:
    container_name: latest-earthquakes-ph-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: "latest-earthquakes-ph-backend:latest"
    depends_on:
      - "mongodb"
      - "redis"
    expose:
      - "5000"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    networks:
      app-network:
        ipv4_address: 172.22.0.3

  mongodb:
    container_name: mongodb
    image: "mongo:4.4.12"
    volumes:
      - mongodb-data:/data/db
    expose:
      - "27017"
    networks:
      app-network:
        ipv4_address: 172.22.0.4

  redis:
    container_name: redis
    image: "redis:latest"
    expose:
      - "6379"
    networks:
      app-network:
        ipv4_address: 172.22.0.5

  geoserve-db:
    build:
      context: ../hazdev-geoserve-ws
      dockerfile: Dockerfile-db
    image: "usgs/hazdev-geoserve-db:latest"
    environment:
      - DATALOAD_DIR=/tmp/dataload
      - DB_ADMIN_USER=postgres
      - DB_ADMIN_PASSWORD=sysop-admin-postgres
      - DB_LOAD_TYPE=incremental
      - DB_NAME=earthquake
      - DB_USER=web
      - DB_PASS=sysop-postgres
      - DB_SCHEMA=geoserve
      - DB_ADMIN_DSN=pgsql:dbname=earthquake
      - PGDATA=/var/lib/postgresqsl/data/pgdata
      - POSTGRES_PASSWORD=sysop-admin-postgres
    volumes:
      # volume to store downloaded data files
      - ../hazdev-geoserve-ws/data/dataload:/tmp/dataload
      # volume to store database data files
      - ../hazdev-geoserve-ws/data/pgdata:/var/lib/postgresqsl/data/pgdata
    networks:
      app-network:
        ipv4_address: 172.22.0.6

  geoserve-ws:
    build:
      context: ../hazdev-geoserve-ws
      dockerfile: Dockerfile-ws
    image: "usgs/hazdev-geoserve-ws:latest"
    environment:
      - DB_DSN=pgsql:host=geoserve-db;port=5432;dbname=earthquake
      - DB_USER=web
      - DB_PASS=sysop-postgres
      - DB_SCHEMA=geoserve
    volumes:
      # volumes for local dev
      - ../hazdev-geoserve-ws/src/htdocs:/var/www/apps/hazdev-geoserve-ws/htdocs
      - ../hazdev-geoserve-ws/src/lib:/var/www/apps/hazdev-geoserve-ws/lib
    expose:
      - "80"
    networks:
      app-network:
        ipv4_address: 172.22.0.7

volumes:
  mongodb-data:

networks:
  app-network:
    name: latest-earthquakes-ph
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16


