# Stage 1: base, minimal setup for dev, shall contain non-js deps.
#          To be bind-mounted to local dev files (includint node_modules)
FROM node:14-alpine as base

LABEL version="1.0"
LABEL description="Base docker image for LatestEarthquakesPH back-end"
LABEL maintainer=["cpsanchez@science.upd.edu.ph"]

EXPOSE 5000

WORKDIR /app

# add non-js deps (for deps other than node_modules)
RUN apk add --no-cache python3 make g++

# Stage 2: prod, inherits base, adds src code, pre-installs js deps
# TODO: Test for production build
FROM base as prod

RUN apk add dumb-init

# install node modules
COPY --chown=node:node package*.json ./
RUN npm ci --loglevel verbose

# copy codebase
COPY --chown=node:node . ./


USER node
CMD ["dumb-init", "node", "index.js"]




