version: '3.9'

services:
  backend:
    container_name: earthquake-hub-backend-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: "base" # select dockerfile stage to use
    image: "earthquake-hub-backend-dev:1.0.0"
    volumes:
      # bind local dir to reflect changes in container
      # NOTE: includes everything, including all those in .dockerignore, specifically .env
      - ./:/app
    depends_on:
      - "mongodb"
      - "redis"
      - "mysql"
    expose:
      - "5000"
    extra_hosts:
       - "host.docker.internal:host-gateway"
    networks:
      app-network:
        ipv4_address: 172.22.0.3
    # set command to only install node_modules if not present, then startDev
    command: npm run start:dev

  mongodb:
    container_name: mongodb
    image: "mongo:5.0"
    volumes:
      - earthquake-hub-mongodb-data:/data/db
    expose:
      - "27017"
    networks:
      app-network:
        ipv4_address: 172.22.0.4
    command: --quiet # reduce logs

  redis:
    container_name: redis
    image: "redis:6.2.5"
    expose:
      - "6379"
    networks:
      app-network:
        ipv4_address: 172.22.0.5

  mysql:
    container_name: mysql
    image: "mysql:8.0.32"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: ${MYSQL_USER} # will automatically be replaced by values in .env in the same dir
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NAME}
    volumes:
      # init db contents by binding sample seiscomp data from host into docker-entrypoint-initdb.d
      - ./dev/sample_data/seiscompDB.sql:/docker-entrypoint-initdb.d/seiscompDB.sql
    ports:
      - "3306:3306" # like in production, mysql should be connectable through "host.docker.internal:host-gateway"
                    # this mirrors a mysql service running locally on host machine

volumes:
  earthquake-hub-mongodb-data:
    external: true # same volume used by other containers
    name: earthquake-hub-mongodb-data

networks:
  app-network:
    name: earthquake-hub-backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16


